# Generated by Django 6.0.6 on 2026-06-17 07:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threatintel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory',
            name='recommended_mitigation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='advisory',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='advisory_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='new_event_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asn',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='asn',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='asn',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=50),
        ),
        migrations.CreateModel(
            name='AttackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=512, unique=True)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('dst_ip', models.CharField(blank=True, max_length=45)),
                ('dst_port', models.CharField(blank=True, max_length=10)),
                ('src_port', models.CharField(blank=True, max_length=10)),
                ('event_timestamp', models.CharField(blank=True, max_length=64)),
                ('dst_host', models.CharField(blank=True, max_length=255)),
                ('proto', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='threatintel.analysisrun')),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='threatintel.asn')),
                ('malware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='threatintel.malware')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
