# Generated by Django 6.0.6 on 2026-07-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threatintel', '0002_advisory_recommended_mitigation_advisory_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisory',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=20),
        ),
    ]
