# Generated by Django 6.0.6 on 2026-07-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threatintel', '0004_advisory_org_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory',
            name='html_content',
            field=models.TextField(blank=True),
        ),
    ]
