# Generated by Django 6.0.6 on 2026-06-18 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnownASN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn_number', models.CharField(max_length=50, unique=True)),
                ('operator_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'analyzer_knownasn',
            },
        ),
        migrations.CreateModel(
            name='KnownMalware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'analyzer_knownmalware',
            },
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder_name', models.CharField(default='', max_length=500)),
                ('total_rows', models.IntegerField(default=0)),
                ('seen_combos_count', models.IntegerField(default=0)),
                ('unique_asns', models.IntegerField(default=0)),
                ('unique_malwares', models.IntegerField(default=0)),
                ('unique_ips', models.IntegerField(default=0)),
                ('asn_stats', models.JSONField(default=list)),
                ('malware_stats', models.JSONField(default=list)),
                ('ip_stats', models.JSONField(default=list)),
                ('new_malwares', models.JSONField(default=list)),
                ('output_dir', models.CharField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('error', 'Error')], default='done', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analyzer_analysisrun',
                'ordering': ['-created_at'],
            },
        ),
    ]
