# Generated by Django 6.0.6 on 2026-06-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='is_first_run',
            field=models.BooleanField(default=False, help_text='True when seen_combos.txt was empty at run start (baseline run).'),
        ),
    ]
